name: Update JSON from Google Sheets

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Use any Python version compatible with your script

    - name: Install Dependencies
      run: |
        pip install requests

    - name: Run Script
      run: python bullish.py

    - name: Commit and Push Changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add bullish_data.json
        git commit -m "Update JSON file from Google Sheets"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
